# Diagonalization and Applications Problem Set
## Problem 1
![title](images/q1.png)

In [8]:
import numpy as np
from numpy import linalg as la

T_1 = np.array([[6, 2], [-1, 3]])
C_1 = np.array([[1, 1], [1, 2]])

# Solve for eigenvalues by applying T to each C_i col of C
print(C_1[:, 0]@T_1)
eig_1 = 5
print(C_1[:, 1]@T_1)
eig_2 = 4
# Note that c@T in numpy is equiavlent to Tc irl.

# For learning sake let's use the linalg eigen solver function provided in numpy
# to do this in the next question.
D_1 = np.array([[5, 0], [0, 4]])
print('Problem 1 diagonal matrix D: \n', D_1)

[5 5]
[4 8]
Problem 1 diagonal matrix D: 
 [[5 0]
 [0 4]]


## Problem 2

![title](images/q2.png)

In [10]:
T_2 = np.array([[2, 0], [7, -1]])
print(la.eigvals(T_2))
# lets see if we can construct a diagonal matrix of eigenvalues directly:
D_2 = np.diag(la.eigvals(T_2))
print(D_2)

# Yay there we have it, a manually and partially complete eigendecomposition.



[-1.  2.]
[[-1.  0.]
 [ 0.  2.]]


## Problem 3

![title](images/q3.png)

In [13]:
T_3 = np.array([[1, 2], [0, -1]])

# Continuing our exploration of numpy's utility functions, let's now
# sequentially step through building an eigendecomposition of the map T_3:

eigvals_3, eigvectors_3 = la.eig(T_3)
print(eigvals_3, '\n', eigvectors_3)

# Now build the diagonal matrix of T_3's eigenvalues
D_3 = np.diag(eigvals_3)
print("Problem 3 ans: \n", D_3)

[ 1. -1.] 
 [[ 1.         -0.70710678]
 [ 0.          0.70710678]]
Problem 3 ans: 
 [[ 1.  0.]
 [ 0. -1.]]


## Problem 4

![title](images/q4.png)

In [14]:
# Now we wish to solve for T_4 given D_4, C_4 and inv(C_4):
C_4 = np.array([[1, 0], [-2, 1]])
C_4_inv = la.inv(C_4)
# To avoid typing error i'm just going to set a = 1
a = 1
D_4 = np.array([[a, 0], [0, a]])
# Note T = C^-1DC, so in numpy we likely reverse the multiplication order.
T_4 = C_4@D_4@C_4_inv
print('Problem 4 ans: \n', T_4)

Problem 4 ans: 
 [[1. 0.]
 [0. 1.]]


## Problem 5

![title](images/q5.png)

In [16]:
# To confirm something let me test the left most matrix on the 
# right side of the equals sign is in fact the inverse of the rightmost
# matrix on the ride sight of the equals sign.

C_5 = np.array([[2, -1], [-1, 1]])
print(la.inv(C_5))

# Okay cool. Now let's just compute T^3.
# The whole point of this question is to demonstrate you can simply
# take the D^3 which is multiplying 5^3 and 4^3,
# then take the D' = D^3 and execute the matrix multiplication to efficiently
# arrive at T^3

# We will use la library to arrive at the some answer in an elegant way:
T_5 = np.array([[6, 2], [-1, 3]])
eigvals_5, right_eigvectors_5 = la.eig(T_5)
T_5_cubed = right_eigvectors_5 @ la.matrix_power(np.diag(eigvals_5), 3) @ la.inv(right_eigvectors_5)
print('Problem 5 ans: \n', T_5_cubed)

# Note matrix power just takes ndarray and raises it to nth power.

[[1. 1.]
 [1. 2.]]
Problem 5 ans: 
 [[186. 122.]
 [-61.   3.]]


## Problem 6

![title](images/q6.png)

In [17]:
# Again this problem has the same form as before, we don't need to be concerned about the tricky
# fractions in the righmost matrix because ultimately we are just concerned with cubing the middle
# diagonal matrix.

T_6 = np.array([[2, 0], [7, -1]])
eigvalues_6, right_eigvectors_6 = la.eig(T_6)
T_6_cubed = right_eigvectors_6 @ la.matrix_power(np.diag(eigvalues_6), 3) @ la.inv(right_eigvectors_6)
print('Problem 6 ans: \n', T_6_cubed)

Problem 6 ans: 
 [[ 8.  0.]
 [21. -1.]]


## Problem 7

![title](images/q7.png)

In [20]:
T_7 = np.array([[1, 2], [0, -1]])
eigvals_7, right_eigvectors_7 = la.eig(T_7)
T_7_cubed = right_eigvectors_7 @ la.matrix_power(np.diag(eigvals_7), 5) @ la.inv(right_eigvectors_7)
print('Problem 7 ans: \n', T_7_cubed)

Problem 7 ans: 
 [[ 1.  2.]
 [ 0. -1.]]
